name: 'Github action demo Raju Datla'
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '15 6 * * 0'
jobs: 
  build:  
    runs-on: ubuntu-latest   
    steps:
     - run: "echo started steps"
     - run: "echo :sparkles: This run was triggered by: ${{ github.event_name }}"
     - run: "echo :sunglasses: The name of the current branch is: ${{ github.ref }}"
      
     - uses: actions/checkout@v3.5.3
      
     - name: "List repo files" 
       run: |
         echo "Here's a list of our files!"
         echo "${{ github.repository }} contains these files:"
         tree
